version: '3.8'
services:
  tearsheet:
    build: .
    container_name: tearsheet
    ports:
      - "5001:5001"
    environment:
      #- SECRET_KEY=${SECRET_KEY}
      #- FLASK_ENV=${FLASK_ENV:-production}
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
