version: '3.8'
services:
  quantstatswebapp:
    build: .
    container_name: quantstatswebapp
    ports:
      - "5001:5000"
    environment:
      #- SECRET_KEY=${SECRET_KEY}
      #- FLASK_ENV=${FLASK_ENV:-production}
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
